### ISSUE TITLE
Fix compilation on rpi1

### ISSUE THREAD

**Issue by GuillaumeLazar** [neuronalmotion/qtrpi#32]
qt modules seems ok but the example qopenglwidget cannot but generated

`
guillaume@desktop-linux:/opt/qtrpi/raspi/qt5/bin$ rcc
rcc: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/rcc': No such file or directory
`

**Comment by synapticvoid** [comment]
Making a proper clean of `modules` and `qtpi` seems to fix the issue. Some artefacts of an old compilation must be hidden somewhere :(
