### ISSUE TITLE
Add QSerial module

### ISSUE THREAD

**Issue by synapticvoid** [neuronalmotion/qtrpi#43]
http://code.qt.io/cgit/qt/qtserialport.git/

**Comment by nbkhwjm** [comment]
how can i help push this forward?

**Comment by GuillaumeLazar** [comment]
Hi @nbkhwjm, we updated the [README.md](https://github.com/neuronalmotion/qtrpi/blob/develop/README.md) with instructions on _how to add a new Qt module in QtRpi?_

In principle, the target module to add is ```qtserialport``` (http://code.qt.io/cgit/qt/qtserialport.git/) but some other dependencies may be needed.

**Comment by nbkhwjm** [comment]
:-) WOOHOO... thanks all..
