### ISSUE TITLE
deploy_qtrpi.sh script has hard coded username

### ISSUE THREAD

**Issue by nbkhwjm** [neuronalmotion/qtrpi#45]
the deploy script uses the hard coded user account of "pi" to set the file owner:group, which prevents other user accounts from succeeding when used to install on the pi.
 
**ssh $TARGET_HOST 'sudo mkdir /usr/local/qt5pi ; sudo chown -R pi:pi /usr/local/qt5pi'**

suggest something like this like using cut, sed or awk on QTRPI_TARGET_HOST

nbkhwjm@Pi-Builder:~/qtrpi$ echo $QTRPI_TARGET_HOST | cut -d@ -f1
nbkhwjm

I had to manually change the owner group then rerun the script without --prepare-rpi

**Comment by GuillaumeLazar** [comment]
Thanks @nbkhwjm for your idea, we will update it soon.
