### ISSUE TITLE
full screen problem!

### ISSUE THREAD

**Issue by sabrabano0** [neuronalmotion/qtrpi#61]
i fallowed your video step by step
hi i can run a qt remote debug on raspi but on the screen of raspi its full screen and i cant exit of that !

i have below error Unable to query physical screen size, defaulting to 100 dpi. To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).

i added below to ~/.bashrc on raspi

```
export QT_QPA_EGLFS_PHYSICAL_WIDTH=528 
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=295 
export QT_QPA_FONTDIR=/usr/share/fonts/truetype/dejavu
```

but its dosnt work , i just solve font by adding its font to below directory: usr/local/qt5pi/lib/fonts

i also did below cmd but i/m not sure its right of not being full screen

`./<program name> -platform xcb`

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted
```

help me please!

**Comment by hardikharpal** [comment]
having same issue..

Debugging starts
Listening on port 10000
Remote debugging from host 192.168.2.106
Process /home/pi//textfinder created; pid = 1065
Could not load shared library symbols for 3 libraries, e.g. /usr/local/qt5pi/lib/libQt5Widgets.so.5.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?Could not load shared library symbols for 3 libraries, e.g. /usr/local/qt5pi/plugins/platforms/libqeglfs.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?Could not load shared library symbols for /usr/local/qt5pi/plugins/egldeviceintegrations/libqeglfs-brcm-integration.so.
Do you need "set solib-search-path" or "set sysroot"?Could not load shared library symbols for /usr/local/qt5pi/plugins/imageformats/libqgif.so.
Do you need "set solib-search-path" or "set sysroot"?Could not load shared library symbols for /usr/local/qt5pi/plugins/imageformats/libqico.so.
Do you need "set solib-search-path" or "set sysroot"?Could not load shared library symbols for /usr/local/qt5pi/plugins/imageformats/libqjpeg.so.
Do you need "set solib-search-path" or "set sysroot"?Could not load shared library symbols for 2 libraries, e.g. /usr/local/qt5pi/plugins/imageformats/libqsvg.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).


I tried 
added below to ~/.bashrc on raspi

export QT_QPA_EGLFS_PHYSICAL_WIDTH=528 
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=295 
export QT_QPA_FONTDIR=/usr/share/fonts/truetype/dejavu
but its dosnt work , i just solve font by adding its font to below directory: usr/local/qt5pi/lib/fonts

**Comment by hardikharpal** [comment]
@sabrabano0 did find any solution...
@synapticvoid  any suggestion.....

**Comment by sabrabano0** [comment]
no i didnt, if you found out share here....
i read somwehere about it, that eglfs is a platfoem to work in full screen mode,
i try to work with other platforms but ....
@hardikharpal

**Comment by hardikharpal** [comment]
I am going to fresh try procedure shown here for qt 5.9 ..http://www.bytran.org/qtrpicrosscompile.htm will let you know about outcome..

**Comment by GuillaumeLazar** [comment]
The EGLFS backend is the best for performance on a Raspberry Pi 3. You don't need to start the X11 server, you can use the GPU and so run some OpenGL applications. The restriction is a single fullscreen window.

More information here: http://doc.qt.io/qt-5/embedded-linux.html#eglfs 

> EGLFS forces the first top-level window (be it either a QWidget or a QQuickView) to become fullscreen. 

More investigation should be done to configure / compile / run a "window" application with QtRpi
