### ISSUE TITLE
Libpcre16.so.3 not found

### ISSUE THREAD

**Issue by jekajarkov** [neuronalmotion/qtrpi#75]
Hi,
I done the full install. On a pi2@jessy. All seem be fine. Then I compiled my qt qml app and upload it to the pi. By trying to start it I got the first  error libpng not found. So I take a quick research and install the lib. Now I have an error libpcre16.so.3 not found. I also try to google it and install but nothing help.

**Comment by synapticvoid** [comment]
Hi there,
Have you tried to install the libpcre package with `apt-get install libpcre3-dev`?

**Comment by jekajarkov** [comment]
Hi,

Thanks for your response. Yes I already install that package, but that's not helped



----- Nachricht beantworten -----
Von: "Robin Penea" <notifications@github.com>
An: "neuronalmotion/qtrpi" <qtrpi@noreply.github.com>
Cc: "jekajarkov" <eugenschreiber@hotmail.com>, "Author" <author@noreply.github.com>
Betreff: [neuronalmotion/qtrpi] Libpcre16.so.3 not found (#75)
Datum: Do., Nov. 23, 2017 09:48


Hi there,
Have you tried to install the libpcre package with apt-get install libpcre3-dev?

**Comment by synapticvoid** [comment]
Alright, let's roll up our sleeves !

* Try to find if libpcre16.so.3 exists on you system with `find /usr/ -name libpcre16.so.3`. 
* If you have no result, maybe you can find the real lib with `find /usr/ -name libpcre16.so*`.
* If you have a result for this last search, you can create the symlink yourself with:
`sudo ln -s <directory of libpcre16.so>/libpcre16.so <directory of lbpcre16.so/libpcre16.so.3`

**Comment by jekajarkov** [comment]
ok thats the steps I done. 

try to install the package again.
"sudo apt-get install libpcre3-dev"
--> libpcre3-dev is already the newest version.

try to find with "find /usr/ -name libpcre16.so.3
--> no result

try to find with "find /usr/ -name libpcre16.so*
--> no result

**Comment by jekajarkov** [comment]
unfortunately it does not work either.


--> Unable to locate package libpcre16-3

----- Nachricht beantworten -----
Von: "Robin Penea" <notifications@github.com>
An: "neuronalmotion/qtrpi" <qtrpi@noreply.github.com>
Cc: "jekajarkov" <eugenschreiber@hotmail.com>, "Author" <author@noreply.github.com>
Betreff: [neuronalmotion/qtrpi] Libpcre16.so.3 not found (#75)
Datum: Fr., Nov. 24, 2017 09:46


What about installing libpcre16-3 with sudo apt install libpcre16-3?

**Comment by GuillaumeLazar** [comment]
- What about a simple Qt Widget application (not a QML application)?
- Your rpi2 jessie OS is updated?

**Comment by jekajarkov** [comment]
Hi,
yes I updated the OS via sudo apt-get update but that not helped.
Actually I used a yocto project image. I compiled the application on my Ubuntu system with qtrpi and download it to the pi.
Now it's running.

**Comment by ucondua** [comment]
I made a full ctrp and get a lot of mistakes, I can not handle this 
cnd @ d: ~ $ sudo apt install libpcre16-3
Reading package lists ... Done
Building dependency tree
Reading state information ... Done
E: Unable to locate package libpcre16-3

**Comment by ucondua** [comment]
I install all packages, but 
QML debugging is enabled. Only use this in a safe environment.
This application failed to start because it could not find or load the Qt platform plugin "eglfs"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Процесс завершён сигналом

**Comment by RobinChap** [comment]
You can also try to recompile your eglfs platform
If you cross compiled like I did :

`cd ~/raspi/qtbase/src/plugin/platforms/eglfs`
`~/raspi/qt5/bin/qmake`
`make`
`make install`

**Comment by ucondua** [comment]
Hello!
I went the other way. I installed the missing libraries and installed sudo apt-get install raspberrypi-ui-mods. It works. It is right?
But I have one problem.
I installed QtGraphicaleffects and it works for me, but I can not enable the designer to generate an error. What to do?
Thank you.
![screenshot 2018-03-23 22-19-44](https://user-images.githubusercontent.com/33059492/37849357-69d3b21e-2ee8-11e8-997e-9017fbc9df39.png)

**Comment by ucondua** [comment]
The graphic effects work! But does not allow to include a graphic designer, an error

"/home/reanon/Qt5.8.0/5.8/gcc_64/bin/qmlplugindump" returned the exit code: 3.
Arguments: -nonrelocatable QtGraphicalEffects 1.0.
Error parsing dependencies file <outputOfQmlimportscanner>: illegal value at 0
failed to promethod of qmlimportscanner
QQmlComponent: Component is not ready
file: ///opt/qtrpi/raspi/qt5pi/qml/typelist.qml: 2: 1: plugin can not be loaded for module "QtGraphicalEffects": '/opt/qtrpi/raspi/qt5pi/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.so 'is an invalid ELF object (wrong cpu architecture)

What to do?
