### ISSUE TITLE
qmake-qtrpi not work in CLI

### ISSUE THREAD

**Issue by sqn175** [neuronalmotion/qtrpi#76]
Hi, 

  Thanks for your nice work. I successfully completed the guide, and get things installed. But error occurs when I use qmake-qtrpi in CLI, and I can not add the qmake-qtrpi to Qt creator qt version.
  The error is:
``
sqn@sqn-T460p:/opt/qtrpi/bin$ qmake-qtrpi -v
``
``
 qmake-qtrpi: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by qmake-qtrpi)
``

Btw, I DO have a `libstdc++.so.6` in `/opt/qtrpi/raspbian/sysroot-minimal/usr/lib/arm-linux-gnueabihf` but it's not linked. 

I'm using Ubuntu14.04 64bit with rpi-zeroW.

**Comment by GuillaumeLazar** [comment]
Hi,

Thanks for your message.

"qmake-qtrpi" should be a symbolic link to "/opt/qtrpi/raspi/qt5/bin/qmake", you can check it with:
```bash
ls -l /opt/qtrpi/raspi/qt5/bin/qmake
```

Also, can you post the console output of:
```bash
/opt/qtrpi/raspi/qt5/bin/qmake -query
```

**Comment by GuillaumeLazar** [comment]
Please also notice that:
* using qtrpi with a **rpi-zero** is untested (we only performed some tests on the **rpi 1, 2 and 3**)
* qtrpi only support Raspbian Jessie (not Raspbian Stretch)

**Comment by sqn175** [comment]
Hi, @GuillaumeLazar 

 Thanks for your quick reply. I upgrade my host pc GCC version from 4.8 to 4.9, and get things worked.

  Now, the output of : 
`/opt/qtrpi/raspi/qt5/bin/qmake -query`

``sqn@sqn-T460p:/opt/qtrpi/bin$ /opt/qtrpi/raspi/qt5/bin/qmake -query
QT_SYSROOT:/opt/qtrpi/raspbian/sysroot
QT_INSTALL_PREFIX:/opt/qtrpi/raspi/qt5pi
QT_INSTALL_PREFIX/dev:/usr/local/qt5pi
QT_INSTALL_ARCHDATA:/opt/qtrpi/raspi/qt5pi
QT_INSTALL_ARCHDATA/dev:/usr/local/qt5pi
QT_INSTALL_DATA:/opt/qtrpi/raspi/qt5pi
QT_INSTALL_DATA/dev:/usr/local/qt5pi
QT_INSTALL_DOCS:/opt/qtrpi/raspi/qt5pi/doc
QT_INSTALL_DOCS/dev:/usr/local/qt5pi/doc
QT_INSTALL_HEADERS:/opt/qtrpi/raspi/qt5pi/include
QT_INSTALL_HEADERS/dev:/usr/local/qt5pi/include
QT_INSTALL_LIBS:/opt/qtrpi/raspi/qt5pi/lib
QT_INSTALL_LIBS/dev:/usr/local/qt5pi/lib
QT_INSTALL_LIBEXECS:/opt/qtrpi/raspi/qt5pi/libexec
QT_INSTALL_LIBEXECS/dev:/usr/local/qt5pi/libexec
QT_INSTALL_BINS:/opt/qtrpi/raspi/qt5pi/bin
QT_INSTALL_BINS/dev:/usr/local/qt5pi/bin
QT_INSTALL_TESTS:/opt/qtrpi/raspi/qt5pi/tests
QT_INSTALL_TESTS/dev:/usr/local/qt5pi/tests
QT_INSTALL_PLUGINS:/opt/qtrpi/raspi/qt5pi/plugins
QT_INSTALL_PLUGINS/dev:/usr/local/qt5pi/plugins
QT_INSTALL_IMPORTS:/opt/qtrpi/raspi/qt5pi/imports
QT_INSTALL_IMPORTS/dev:/usr/local/qt5pi/imports
QT_INSTALL_QML:/opt/qtrpi/raspi/qt5pi/qml
QT_INSTALL_QML/dev:/usr/local/qt5pi/qml
QT_INSTALL_TRANSLATIONS:/opt/qtrpi/raspi/qt5pi/translations
QT_INSTALL_TRANSLATIONS/dev:/usr/local/qt5pi/translations
QT_INSTALL_CONFIGURATION:/opt/qtrpi/raspi/qt5pi/etc/xdg
QT_INSTALL_CONFIGURATION/dev:/usr/local/qt5pi/etc/xdg
QT_INSTALL_EXAMPLES:/opt/qtrpi/raspi/qt5pi/examples
QT_INSTALL_EXAMPLES/dev:/usr/local/qt5pi/examples
QT_INSTALL_DEMOS:/opt/qtrpi/raspi/qt5pi/examples
QT_INSTALL_DEMOS/dev:/usr/local/qt5pi/examples
QT_HOST_PREFIX:/opt/qtrpi/raspi/qt5
QT_HOST_DATA:/opt/qtrpi/raspi/qt5
QT_HOST_BINS:/opt/qtrpi/raspi/qt5/bin
QT_HOST_LIBS:/opt/qtrpi/raspi/qt5/lib
QMAKE_SPEC:linux-g++
QMAKE_XSPEC:devices/linux-rasp-pi-g++
QMAKE_VERSION:3.0
QT_VERSION:5.7.0
``

But I still dont know why this worked?

**Comment by GuillaumeLazar** [comment]
I'm glad to hear that it works.

Effectively GCC 4.8 is quite old. A recent GCC version is always a good thing. 
The issue was maybe an incompatibility with a too old version of GCC.

We should add GCC version 4.9 at the minimum requirement in the qtrpi documentation

**Comment by sqn175** [comment]
Thanks for your work again.
And it's proved that qtrpi is compatible with Rpi-zeroW.

**Comment by GuillaumeLazar** [comment]
It's a good news. Can you share with us the qtrpi environment variables used for your rpi-zerow?
```bash
QTRPI_QT_VERSION
QTRPI_TARGET_DEVICE
```

**Comment by sqn175** [comment]
It's:
`QTRPI_QT_VERSION='5.7.0'
 QTRPI_TARGET_DEVICE='linux-rasp-pi-g++'
`
Rpi ZeroW use the same Core type as Rpi: [RaspberryPI models comparison](http://socialcompare.com/en/comparison/raspberrypi-models-comparison)
