### ISSUE TITLE
eg2

### ISSUE THREAD

**Issue by gpmontt** [neuronalmotion/qtrpi#80]
HI we try it to compile external qt-modules,
I found this issue in QT-forum
https://bugreports.qt.io/browse/QTBUG-62216
it`s this true ??

**Comment by GuillaumeLazar** [comment]
This Qt bug report seems to only affect Qt version >= 5.8.0 on Raspbian Stretch. 

These versions are currently **unsupported** by QtRpi that only support:
* Qt 5.6.2 and Qt 5.7.0
* Raspbian Jessie

Check the [README.md](https://github.com/neuronalmotion/qtrpi/blob/master/README.md) and the [Wiki](https://github.com/neuronalmotion/qtrpi/wiki).
